# Generated by Django 2.1.7 on 2019-05-31 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_post_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='writer',
            new_name='user',
        ),
    ]
